version: 2.1

orbs:
   win: circleci/windows@1.0.0

workflows:
  test:
    jobs:
      - build-run-linux:
          context: hello-world-demos
      - build-windows

  test-daily:
    triggers:
    - schedule:
        cron: "0 6 * * *"
        filters:
          branches:
            only: main
    jobs:
    - build-run-linux:
        context: hello-world-demos

# This CI build ensures that the demo both compiles and works correctly. For the runtime test,
# we use an SDK key and flag key that are passed in via the CircleCI project configuration;
# the flag is configured to return a true value.

jobs:
  build-run-linux:
    docker:
      - image: circleci/openjdk:14-jdk-buster
    steps:
      - checkout
      - run:
          name: show dependency versions
          command: ./gradlew dependencies
      - run:
          name: insert SDK key and flag key into demo code
          command: |
            sed -i.bak "s/SDK_KEY *= *\".*\"/SDK_KEY = \"${LD_HELLO_WORLD_SDK_KEY}\"/" src/main/java/Hello.java
            sed -i.bak "s/FEATURE_FLAG_KEY *= *\".*\"/FEATURE_FLAG_KEY = \"${LD_HELLO_WORLD_FLAG_KEY_WITH_TRUE_VALUE}\"/" src/main/java/Hello.java
      - run:
          name: build demo
          command: ./gradlew build
      - run:
          name: run demo
          command: |
            ./gradlew run | tee output.txt
            grep "is true for this context" output.txt || (echo "Flag did not evaluate to expected true value" && exit 1)

  build-windows:
    executor:
      name: win/vs2019
      shell: powershell.exe
    steps:
      - checkout
      - run:
          name: install OpenJDK
          command: |
            $ProgressPreference = "SilentlyContinue"  # prevents console errors from CircleCI host
            iwr -outf openjdk.msi https://developers.redhat.com/download-manager/file/java-11-openjdk-11.0.5.10-2.windows.redhat.x86_64.msi
            Start-Process msiexec.exe -Wait -ArgumentList '/I openjdk.msi /quiet'
      - run: .\gradlew.bat --no-daemon dependencies  # must use --no-daemon because CircleCI in Windows will hang if there's a daemon running
      - run: .\gradlew.bat --no-daemon build  # must use --no-daemon because CircleCI in Windows will hang if there's a daemon running
